project:
  type: website

website:
  title: "Postos no ano de 2010"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chinaskinho
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

publish:
  method: gh-pages